### ISSUE TITLE
Create hyperlinks

### ISSUE THREAD

**Issue by NazorMaizer** [NazorMaizer/NazorMaizer.github.io#1]
1) абсолютную гиперссылку на главную страницу сайта kubsu.ru;
2) абсолютную на главную сайта kubsu.ru в протоколе https;
3) ссылку-изображение;
4) сокращенную ссылку на внутреннюю страницу;
5) сокращенную ссылку на главную страницу;
6) ссылку на фрагмент текущей страницы;
7) ссылку с тремя параметрами в URL;
8) ссылку с параметром id в URL;
9) относительную на страницу в текущем каталоге;
10) относительную на страницу в каталоге about;
11) относительную на страницу в каталоге уровнем выше текущего;
12) относительную на страницу в каталоге двумя уровнями выше;
13) контекстную в тексте абзаца;
14) ссылку на фрагмент страницы стороннего сайта;
15) ссылки из прямоугольных и круглых областей картинки (HTML-тег map);
16) ссылку с пустым href;
17) ссылку без href;
18) ссылку, по которой запрещен переход поисковикам;
19) запрещенную для индексации поисковиками;
20) нумерованный список ссылок с подписями title;
21) ссылку на файл на сервере FTP с авторизацией;

**Comment by NazorMaizer** [comment]
- [ ] абсолютную гиперссылку на главную страницу сайта kubsu.ru;

**Comment by NazorMaizer** [comment]
### Tasks
- [ ] абсолютную гиперссылку на главную страницу сайта kubsu.ru;
- [ ] абсолютную на главную сайта kubsu.ru в протоколе https;
- [ ] ссылку-изображение;
- [ ] сокращенную ссылку на внутреннюю страницу;
- [ ] сокращенную ссылку на главную страницу;
- [ ] ссылку на фрагмент текущей страницы;
- [ ] ссылку с тремя параметрами в URL;
- [ ] ссылку с параметром id в URL;
- [ ] относительную на страницу в текущем каталоге;
- [ ] относительную на страницу в каталоге about;
- [ ] относительную на страницу в каталоге уровнем выше текущего;
- [ ] относительную на страницу в каталоге двумя уровнями выше;
- [ ] контекстную в тексте абзаца;
- [ ] ссылку на фрагмент страницы стороннего сайта;
- [ ] ссылки из прямоугольных и круглых областей картинки (HTML-тег map);
- [ ] ссылку с пустым href;
- [ ] ссылку без href;
- [ ] ссылку, по которой запрещен переход поисковикам;
- [ ] запрещенную для индексации поисковиками;
- [ ] нумерованный список ссылок с подписями title;
- [ ] ссылку на файл на сервере FTP с авторизацией;
- [ ]
