### ISSUE TITLE
Adjust form file

### ISSUE THREAD

**Issue by NazorMaizer** [NazorMaizer/NazorMaizer.github.io#2]
1) ФИО (текстовое поле);
2) Телефон (поле tel);
3) e-mail (поле email);
4) дата рождения (поле даты);
5) пол (радиокнопки);
6) любимый язык программирования: Pascal, C, C++, JavaScript, PHP, Python, Java,
Haskel, Clojure, Prolog, Scala (множественный выбор из списка);
7) биография (многострочное текстовое поле);
8) с контрактом ознакомлен (а) (чекбокс);
9) кнопка «Сохранить».

**Comment by NazorMaizer** [comment]
### Tasks
- [ ] ФИО (текстовое поле); 
- [ ] Телефон (поле tel); 
- [ ] e-mail (поле email); 
- [ ] дата рождения (поле даты); 
- [ ] пол (радиокнопки); 
- [ ] любимый язык программирования: Pascal, C, C++, JavaScript, PHP, Python, Java, Haskel, Clojure, Prolog, Scala (множественный выбор из списка); 
- [ ] биография (многострочное текстовое поле); 
- [ ] с контрактом ознакомлен (а) (чекбокс); 
- [ ] кнопка «Сохранить».
